<form action="<?php echo Mage::getUrl('helloworld/index/login') ?>" method="post">
    <fieldset>
        <ul>
            <li>
                <label for="username">Username</label>
                <input type="text" id="username" name="username"/>
            </li>
            <li>
                <label for="password">Password</label>
                <input type="text" id="password" name="password" />
            </li>
            <li>
                <input type="submit" value="Login" />
            </li>
        </ul>
    </fieldset>
</form>
<a href="<?php echo Mage::getURl('helloworld');?>">Cancel</a>